### PR TITLE
fix semantics autoheight with scroll views

### PR DESCRIPTION
**Pull request by manu-sncf**
When `SemanticsDebugger` is used with a Scrollable, the semantics boxes are partially displayed :

Capture d’écran 2022-08-16 à 12 29 17

The golden should be like this :

Capture d’écran 2022-08-16 à 12 29 26

The fix only add a few pumps on `screenMatchesGolden` when it detect a `SemanticsDebugger` (5 pumps max if frame are scheduled).

The `autoHeightExtraPumps` allows to add other `Finder` with their number of extra pumps necessary.

Extra pump will be executed if one of the finder is valid and keep the max number of the map.

### CODE REVIEW

**Comment by manu-sncf** [comment]
> Is it possible to use CustomPump? customPump? param instead

Hey ! The customPump is triggered before the final size computation of the screen. Although, SemanticDebugger needs this final size to be displayed correctly and thus, customPump may not be the solution.

**Comment by jscti** [comment]
Could this be reviewed/merged ?
Thanks

**Comment by LDevi** [comment]
Could we have a status for this ? This feature would be welcome.

**Comment by coreysprague** [comment]
@LDevi @agacemi @jscti @manu-sncf 

I deeply apologize, but we have decided to end-of-life this project 😞 

------------------------------------------

This repo is no longer maintained

09/12/2024 Update:

Unfortunately we have made the tough decision to no longer actively maintain this repository. While the package has served us and the community well, we don't have the capacity to give it the attention it deserves.

We realize that this decision means that open pull requests will not be merged. Our hope is that the community will rally and focus their efforts around more actively maintained packages for aiding in golden-based tests.

Once again, we want to thank each and every one of you for your contributions over the years.

Thank you for your understanding.

Best regards,

The eBay Motors App team

**Pull request closed without merging**
