### PR TITLE
Use a null default skip value in testGoldens so it can inherit the group's skip flag

### PR DESCRIPTION
**Pull request by daohoangson**
Related to #97, flutter/flutter#76174

### CODE REVIEW

**Review by fatherOfLegends — APPROVED** [review]
Thanks for recreating this PR.

**Comment by coreysprague** [comment]
closing this. I made the same change in another PR that just merged. Sorry for the delay

**Comment by coreysprague** [comment]
this should be fixed in 0.10.0 @daohoangson

**Comment by daohoangson** [comment]
That's great news. Thank you!

**Pull request closed without merging**
