### PR TITLE
Tag golden tests

### PR DESCRIPTION
**Pull request by kuhnroyal**
This is a very optimistic approach but maybe there is not much more involved.

I can't get my tests to succeed when using the package as local dependency. I have golden diffs of 0.x% related to fonts. This happens on master as well so it is not related to this change.

- [x] add tests

### CODE REVIEW

**Comment by coreysprague** [comment]
awesome. I was going to work on this today. 😄

**Comment by kuhnroyal** [comment]
Feel free, I won't have much time this week, this is just leftovers from friday :)

**Comment by kuhnroyal** [comment]
This seems to work, what do you need to get this in?
A test for the config property?

**Comment by coreysprague** [comment]
I can't think of a good test, unless there is an easy way to inspect the tags of a given test, but even then, it feels a bit pedantic. 

I was ignoring this because it was still in draft.

**Review by coreysprague — APPROVED** [review]
👍

**Comment by coreysprague** [comment]
just published in 0.10.0.

Thanks for your help @kuhnroyal

**Pull request merged**
