### PR TITLE
Use a null default skip value in testGoldens so it can inherit the group's skip flag

### PR DESCRIPTION
**Pull request by daohoangson**
Related to https://github.com/flutter/flutter/pull/76174

### CODE REVIEW

**Review by coreysprague — APPROVED** [review]
👍 this seems good. I think we need to adjust our branching strategy here though. 🤞 null safety will hit stable with the flutter event next week... but the nullable skip? parameter JUST hit flutter master 6 days ago, which means it's probably going to be in the tranche afterwards.

I think it might make more sense for us to keep keep long lived branches that pair up with flutter stable, beta, and master respectively.

Thoughts @fatherOfLegends ?

**Comment by coreysprague** [comment]
actually @daohoangson, one more thing. We should probably update the min supported dart/flutter versions in the pubspec.yaml to reflect this dependency on the new API.

BTW, thanks for doing this 😄

**Comment by daohoangson** [comment]
The commit hasn't made it to dev channel yet so I'm using master for now. After some tinkering with travis, CI is now green.

There is no tag yet so I haven't updated the minimum Flutter version in the pubspec though.

**Comment by coreysprague** [comment]
@daohoangson ugh. I just merged in the null safety branch into master
and it inadvertently closed this. I can't rebase it. Can you re-open it?

**Comment by daohoangson** [comment]
I can't. Is it okie if I open another one?

**Comment by coreysprague** [comment]
@daohoangson please do! Sorry for the hiccup

**Pull request closed without merging**
