### PR TITLE
Support loading new Flutter 3.19 Cupertino font families

### LINKED ISSUE #188: Support loading new Cupertino fonts in Flutter 3.19
Flutter now uses `CupertinoSystemDisplay` and `CupertinoSystemText` font families which are not being overridden when loading fonts.

### PR DESCRIPTION
**Pull request by kuhnroyal**
* fixes #188

### CODE REVIEW

**Comment by RafaelPlantard** [comment]
any news?

**Comment by kuhnroyal** [comment]
Hey @coreysprague, hope everything is alright. Any plans to merge this? And to generally keep this package alive?

**Comment by befirst** [comment]
Please merge it, now it's impossible to test cupertino picker widget without overriding fonts

**Comment by coreysprague** [comment]
@befirst @kuhnroyal @RafaelPlantard 


I deeply apologize, but we have decided to end-of-life this project 😞 

------------------------------------------

This repo is no longer maintained

09/12/2024 Update:

Unfortunately we have made the tough decision to no longer actively maintain this repository. While the package has served us and the community well, we don't have the capacity to give it the attention it deserves.

We realize that this decision means that open pull requests will not be merged. Our hope is that the community will rally and focus their efforts around more actively maintained packages for aiding in golden-based tests.

Once again, we want to thank each and every one of you for your contributions over the years.

Thank you for your understanding.

Best regards,

The eBay Motors App team

**Comment by Wreos** [comment]
@coreysprague  @kuhnroyal 
Hello,
I actively use this package in my tests (more than 100).  Am I allowed to fork your project and publish on my own with different name? If so, on what terms? Should I include ebay copyright?
I plan to continue to support its use.

**Comment by kuhnroyal** [comment]
You can read the LICENSE file and look at the conditions, but please wait a little bit before publishing fork yourself. I contacted eBay via mail and they are currently discussing internally if and how they can hand this project over to the community. They had a lot of people contacting them in this regard.
Having multiple cloned packages published is fragmenting the Flutter ecosystem and doesn't help. Give it a little bit of time please.

**Comment by fatherOfLegends** [comment]
I want to clarify that the concept of golden tests are built into Flutter. You can continue to have golden tests without this package or a clone of it. This package was just intended to make it more convenient to use them for common use cases we had at eBay. Since then several things have improved within flutter_test and some of this package is outdated. I have been working on updating and republishing this package but I want to include several extensions to Goldens that @CaleyD and I have made and use within Agapé. That said I am not sure it will be a drop in replacement. I agree with @kuhnroyal that it isn't great for the community to introduce multiple published forks but you can absolutely copy the relevant pieces into your projects if you need specific behaviors that are not supported by this package in its current state.

**Comment by SAGARSURI** [comment]
Hoping that this package will shift to Flutter community to maintain.

**Comment by ricardoboss** [comment]
For anyone finding this thread, I found this alternative, that seems to do something similar: https://pub.dev/packages/alchemist

**Pull request closed without merging**
