### PR TITLE
Update testing_tools.dart

### PR DESCRIPTION
**Pull request by takassh**
Hi, thank you for publishing this package! It is so useful for us!

I found a subtle need.
`pumpDeviceBuilder` does not have `textScaleSize` argument, so I added it!

### CODE REVIEW

**Comment by coreysprague** [comment]
@takassh thanks for the contribution! Would you mind adding a test to demonstrate the behavior?

**Comment by takassh** [comment]
@coreysprague 
np!
I added a test
it means you can easily compare text scale among another devices

**Review by coreysprague — APPROVED** [review]
thanks! I'll get this out in a new release shortly

**Comment by takassh** [comment]
@coreysprague 
thank you!

**Pull request closed without merging**
